### PR TITLE
bugfix: set index appropriately when expanding char buffer in WriterCharAppender

### PR DESCRIPTION
**Pull request by ashutoshmimani**

### CODE REVIEW

**Comment by jbax** [comment]
Can you please provide a test case that reproduces the bug and ensures this fix actually fixes it?
Thank you for your contribution!

**Comment by ashutoshmimani** [comment]
done. let me know if you need additional info.

**Comment by jbax** [comment]
Excellent catch, thank you so much!

**Comment by jbax** [comment]
Version 2.0.1 released to include this important bugfix. Thanks again!

**Comment by ashutoshmimani** [comment]
Thanks for the quick turnaround!

**Pull request merged**
